name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        HOST_DB: ${{ secrets.HOST_DB }}
        USER_DB: ${{ secrets.USER_DB }}
        PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
        NAME_DB: ${{ secrets.NAME_DB }}
        PORT_DB: ${{ secrets.PORT_DB }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

